# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_changed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
