# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_todo_list', '0002_item_last_changed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='item',
        ),
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
