# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='time',
        ),
    ]
