# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 17:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grumblr', '0005_auto_20161008_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followees',
            field=models.ManyToManyField(related_name='_profile_followees_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
