# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0006_auto_20161008_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_changed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
