# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default=b'mysalt', max_length=42),
        ),
    ]
